<#
.SYNOPSIS
  Sync the CANONICAL AI briefing file to all agent-specific mirrors in one shot.

.DESCRIPTION
  The ONLY file you ever edit manually is:
      .obsidian-vault/CLAUDE.md

  After editing it, run THIS script to push the content out to every
  mirror file that AI agents auto-load (project-root CLAUDE.md,
  .cursorrules, .windsurfrules, .github/copilot-instructions.md,
  and the vault-level generic aliases AGENT.md + AI_BRIEFING.md).

  Every mirror gets a prominent "DO NOT EDIT THIS FILE" warning header
  so you (and the AI) never accidentally edit a mirror instead of the
  canonical source.

  Run from the PROJECT ROOT folder:
      PowerShell>  & .\sync-agent-briefings.ps1

  If you get a ExecutionPolicy warning, run once:
      Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
  Then re-run the script.

.NOTES
  Author : Universal Second Brain Project Template
  Version: 1.0
#>

# ============================================================================
# 1. Setup — resolve paths relative to the PROJECT ROOT
#    (Script must be placed at the project root for this to work.)
# ============================================================================
$ErrorActionPreference = 'Stop'

$Root          = Split-Path -Parent $MyInvocation.MyCommand.Path
$CanonicalRel  = Join-Path '.obsidian-vault' 'CLAUDE.md'
$CanonicalPath = Join-Path $Root $CanonicalRel

if (-not (Test-Path $CanonicalPath)) {
    Write-Error "ERROR: Canonical source not found at: $CanonicalRel"
    Write-Error "Run this script from the PROJECT ROOT folder only."
    exit 1
}

# Read the CANONICAL content ONCE — this is our source of truth.
# NOTE: We use [System.IO.File]::ReadAllText() (NOT Get-Content) because:
#   • PowerShell 5.1 `Set-Content -Encoding UTF8` writes a UTF-8 WITH-BOM file;
#     `Get-Content -Encoding UTF8` correctly reads it, but the round-trip then
#     causes the write side (see §Write step below) to re-emit the BOM on every
#     mirror, which triggers mojibake (`âš ï¸`) downstream in viewers that
#     interpret the byte stream as Latin-1/CP1252 (BUG-004).
#   • File.ReadAllText() defaults to UTF-8 NO-BOM detection on read; paired with
#     File.WriteAllText() below it gives byte-identical, portable UTF-8 on BOTH
#     PowerShell 5.1 (.NET Framework) AND PowerShell 7+ (.NET 5+).
#   • Passing [System.Text.UTF8Encoding]::new($false) explicitly enforces
#     NO-BOM so the contract is the same on every runtime.
$Utf8NoBom    = [System.Text.UTF8Encoding]::new($false)
$CanonicalAbs = (Resolve-Path -LiteralPath $CanonicalPath).Path
$Raw          = [System.IO.File]::ReadAllText($CanonicalAbs, [System.Text.Encoding]::UTF8)

# ============================================================================
# 1b. Strip the canonical-only banner so mirrors do NOT contain contradictory
#     instructions. The canonical file contains a large HTML-comment block
#     near the top with "CANONICAL SOURCE OF TRUTH — EDIT ONLY THIS FILE"
#     plus the mirrors-maintained routing table. When verbatim-copied into
#     mirrors, that block directly contradicts the sync-script prepended
#     "DO NOT EDIT THIS FILE" warning header (BUG-002).
#
#     We identify the block by:
#       • being inside an HTML comment delimiter pair   <!-- ... CANONICAL ... -->
#       • containing the unique marker phrase           "CANONICAL SOURCE OF TRUTH — EDIT ONLY THIS FILE"
#     and remove ONLY that block from $Raw (in-memory)
#     BEFORE any mirror is written. The canonical file on disk is
#     NEVER modified.
#
#     NOTE: the phrase "CANONICAL SOURCE OF TRUTH" also appears in the
#     plain-Markdown File Map section (e.g. "# ✅ CANONICAL SOURCE OF TRUTH
#     (you are here)"). That occurrence is inside Markdown — NOT inside
#     <!-- ... --> — so this regex correctly leaves it untouched.
# ============================================================================
$CanonicalOnlyBlockPattern = '(?s)\r?\n?<!--.*?CANONICAL SOURCE OF TRUTH.*?-->\r?\n?'
$RawStripped = [regex]::Replace($Raw, $CanonicalOnlyBlockPattern, [Environment]::NewLine, [System.Text.RegularExpressions.RegexOptions]::Singleline)

# If the regex matched, $RawStripped differs from $Raw — use it for mirrors.
# If the marker was not found (user customized the banner and removed the
# phrase), we silently fall back to $Raw unmodified rather than aborting.
if ($RawStripped -cne $Raw) {
    $Raw = $RawStripped
}
Remove-Variable RawStripped

# ============================================================================
# 2. Helper: Build the appropriate warning header for each mirror type
# ============================================================================
# IMPORTANT: ⚠️ and — are rendered below via [char] escapes, NOT literal
# glyphs in the .ps1 file. This is DELIBERATE and MUST NOT be reverted:
#   • PowerShell 5.1 parses .ps1 source files using the system default
#     Windows ANSI codepage (typically CP1252/Latin-1) unless the file
#     contains a UTF-8 BOM or a `#requires` directive.
#   • If any developer (or this very script's own File.WriteAllText call
#     in a prior release) re-saves sync-agent-briefings.ps1 without a BOM,
#     literal bytes 0xE2 0x9A 0xA0 for ⚠️ get re-interpreted by PS5.1 as
#     three CP1252 chars ("â\xa0"), then written into every mirror as
#     mojibake — which is exactly the root cause of BUG-004.
#   • [char] Unicode escape sequences parse to the correct code points
#     100% of the time on PS5.1 and PS7+, independent of the .ps1
#     file's on-disk encoding. They are the single portable primitive.
$UnicodeWarnEmoji   = [string][char]0x26A0 + [string][char]0xFE0F   # ⚠️ = WARNING SIGN (U+26A0) + VARIATION SELECTOR-16 emoji-style presentation (U+FE0F)
$UnicodeEmDash      = [string][char]0x2014                          # — = EM DASH (U+2014), used in .cursorrules $Purpose string

function Get-WarningHeader {
    param(
        [Parameter(Mandatory=$true)] [string] $MirrorName,
        [Parameter(Mandatory=$true)] [string] $Purpose,
        [Parameter(Mandatory=$true)] [bool]   $MarkdownStyle = $true
    )

    if ($MarkdownStyle) {
        # Standard HTML comment header for Markdown / .md / copilot-instructions.md files
        @"
<!--
  $UnicodeWarnEmoji  DO NOT EDIT THIS FILE DIRECTLY. AUTOMATICALLY GENERATED MIRROR.

  $Purpose

  Canonical source: .obsidian-vault/CLAUDE.md  (edit ONLY that file)
  Sync command:     & .\sync-agent-briefings.ps1
-->

"@
    }
    else {
        # Hash-comment style for .cursorrules / .windsurfrules / YAML-style files
        @"
# $UnicodeWarnEmoji  DO NOT EDIT THIS FILE DIRECTLY. AUTOMATICALLY GENERATED MIRROR.
#
# $Purpose
#
# Canonical source: .obsidian-vault/CLAUDE.md  (edit ONLY that file)
# Sync command:     & .\sync-agent-briefings.ps1

"@
    }
}

# ============================================================================
# 3. Define every mirror we maintain
#    (Add new entries here to support new AI agent conventions.)
# ============================================================================
$Mirrors = @(
    # ---------- PROJECT ROOT — native agent conventions -------------------
    @{
        Rel     = 'CLAUDE.md'
        Purpose = 'Claude Code CLI by Anthropic auto-loads ./CLAUDE.md from the launch directory. It does not scan subfolders, so this root mirror must exist.'
        StyleMd = $true
    },
    @{
        Rel     = '.cursorrules'
        Purpose = ("Cursor IDE by Anysphere reads .cursorrules at project root as its NATIVE rules file. Loaded first {0} before any code context." -f $UnicodeEmDash)
        StyleMd = $false
    },
    @{
        Rel     = '.windsurfrules'
        Purpose = 'Windsurf IDE by Codeium (Cascade) reads .windsurfrules at project root as its NATIVE rules file.'
        StyleMd = $false
    },
    @{
        Rel     = (Join-Path '.github' 'copilot-instructions.md')
        Purpose = 'GitHub Copilot Agent (VS Code / github.dev) recognizes .github/copilot-instructions.md at project root as its NATIVE project-level briefing. Loaded preferentially.'
        StyleMd = $true
    },
    # ---------- OBSIDIAN VAULT — generic search aliases -------------------
    @{
        Rel     = (Join-Path '.obsidian-vault' 'AGENT.md')
        Purpose = 'Generic alias mirror so any future/unknown AI agent that does semantic search for the KEYWORD "agent" ranks the project briefing highly.'
        StyleMd = $true
    },
    @{
        Rel     = (Join-Path '.obsidian-vault' 'AI_BRIEFING.md')
        Purpose = 'Generic alias mirror so any future/unknown AI agent that does semantic search for the KEYWORD "briefing" ranks the project briefing highly.'
        StyleMd = $true
    }
)

# ============================================================================
# 4. Write every mirror
# ============================================================================
$CreatedDirs = 0
$Written      = 0

foreach ($m in $Mirrors) {
    $DestPath = Join-Path $Root $m.Rel

    # Ensure parent directory exists (for .github/, .vscode/, etc.)
    $DestDir = Split-Path -Parent $DestPath
    if ($DestDir -and -not (Test-Path -LiteralPath $DestDir)) {
        New-Item -ItemType Directory -Path $DestDir -Force | Out-Null
        $CreatedDirs++
    }

    $Header  = Get-WarningHeader -MirrorName (Split-Path -Leaf $DestPath) `
                                  -Purpose    $m.Purpose `
                                  -MarkdownStyle:$m.StyleMd

    $FinalContent = $Header + $Raw

    # Write the file. Use File.WriteAllText() — NOT Set-Content — to guarantee
    # UTF-8 WITHOUT-BOM on both PowerShell 5.1 (.NET Framework, where
    # Set-Content -Encoding UTF8 incorrectly writes UTF-8 WITH-BOM triggering
    # the mojibake + invisible BOM at byte 0 of rule files that IDE parsers may
    # reject; see BUG-004) and PowerShell 7+ (.NET, which already defaults to
    # UTF-8 no-BOM but we enforce the same explicit encoder for parity).
    $DestAbs = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($DestPath)
    [System.IO.File]::WriteAllText($DestAbs, $FinalContent, $Utf8NoBom)
    $Written++

    Write-Host "  [OK] Synced  ->  $($m.Rel)"
}

# ============================================================================
# 5. Final report
# ============================================================================
Write-Host ""
Write-Host "==============================================================="
Write-Host "  [DONE] sync-agent-briefings.ps1 - complete"
Write-Host "==============================================================="
Write-Host "  Canonical source : .obsidian-vault/CLAUDE.md"
Write-Host "  Mirrors updated  : $Written"
Write-Host "  Dirs created     : $CreatedDirs"
Write-Host ""
Write-Host "  Next step: commit code + vault + mirrors together in Git."
Write-Host ""
